# Makefile
# Path to client module
CLIENT_PATH := ./client_module/* 
CLIENT_FILE := ./client_module/client.py

.PHONY: build_client clean_client

build: build_client

build_one_file: build_client_one clean_client

build_client:
	cp -r $(CLIENT_PATH) .

build_client_one:
	#Creates an executable of client.py and its modules in a single file
	pyinstaller --onefile $(CLIENT_FILE)

clean_client:
	# Delete unnecessary files generated by pyinstaller 
	rm -rf build/ *.spec __pycache__

	# Move the executable "/dist" to the root 
	# notdir remove full path and returns word "client"
	mv dist/$(notdir $(CLIENT_FILE:.py=)) .  

	# Remove dist directory
	rmdir dist

clean_py_files:
	# Delete .py files
	rm *.py
	rm -rf __pycache__
