# Makefile
# Path to client module
CLIENT_PATH := ./client_module/* 
CLIENT_FILE := ./client_module/client.py

SERVER_PATH := ./server_module/*
SERVER_FILE := ./server_module/server.c

.PHONY: build_client build_server clean clean_client

build: build_client build_server

build_one_file: build_client_one clean_client build_server

clean: clean_py_files clean_c_files clean_py_one_file

build_client:
	cp -r $(CLIENT_PATH) .

build_server:
	gcc $(SERVER_PATH) -o server -ansi -std=c99 -pedantic -pthread -Wall

build_client_one:
	#Creates an executable of client.py and its modules in a single file
	pyinstaller --onefile $(CLIENT_FILE)

clean_client:
	# Delete unnecessary files generated by pyinstaller 
	rm -rf build/ *.spec __pycache__

	# Move the executable "/dist" to the root 
	# notdir remove full path and returns word "client"
	mv dist/$(notdir $(CLIENT_FILE:.py=)) .  

	# Remove dist directory
	rmdir dist

clean_py_files:
	# Delete .py files
	rm -rf *.py
	rm -rf __pycache__

clean_py_one_file:
	# Delete client files
	rm -rf client

clean_c_files:
	# Delete server files
	rm -rf server